version: 2
updates:
- package-ecosystem: npm
  directory: "/ui-automated-tests"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - tobiasbrown
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.4
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: date-fns
    versions:
    - 2.18.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: "@types/puppeteer"
    versions:
    - 5.4.2
  - dependency-name: puppeteer
    versions:
    - 5.5.0
- package-ecosystem: nuget
  directory: "/subscribers/email.logger/worker"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - tobiasbrown
  ignore:
  - dependency-name: Microsoft.EntityFrameworkCore.Tools
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Sentry.Serilog
    versions:
    - 3.0.1
    - 3.0.7
  - dependency-name: AWSSDK.SQS
    versions:
    - 3.5.1.14
    - 3.5.1.21
  - dependency-name: Serilog.Extensions.Hosting
    versions:
    - 4.1.0
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
- package-ecosystem: nuget
  directory: "/subscribers/logs/worker"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - tobiasbrown
  ignore:
  - dependency-name: Sentry.Serilog
    versions:
    - 3.0.1
    - 3.0.7
  - dependency-name: Serilog.Extensions.Hosting
    versions:
    - 4.1.0
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: AWSSDK.SQS
    versions:
    - 3.5.1.14
    - 3.5.1.21
  - dependency-name: Npgsql
    versions:
    - 5.0.3
  - dependency-name: Moq
    versions:
    - 4.16.0
- package-ecosystem: nuget
  directory: "/subscribers/slack/worker"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - tobiasbrown
  ignore:
  - dependency-name: AWSSDK.SQS
    versions:
    - 3.5.1.14
    - 3.5.1.21
  - dependency-name: Sentry.Serilog
    versions:
    - 3.0.1
    - 3.0.7
  - dependency-name: Serilog.Extensions.Hosting
    versions:
    - 4.1.0
